# from .prompt import (
#     RCA_CAPA_PROMPT,
#     DOMINANT_ROOT_CAUSE_PROMPT,
#     PHASE_I_INVESTIGATION_QA_PROMPT,
#     PHASE_II_INVESTIGATION_QA_PROMPT,
#     RESEARCH_AGENT_PROMPT,
#     HYPOTHESIS_GENERATION_PROMPT,
#     IMPACT_ASSESSMENT_PROMPT,
#     NON_COMPLIANCE_WORDS,
#     TRAINING_MATERIAL_PROMPT,
#     FINAL_SUMMARY_PROMPT,
# )
