name: Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create .env file with secrets
        run: |
          echo "AZURE_OPENAI_ENDPOINT=${{ vars.AZURE_OPENAI_ENDPOINT }}" >> ./.env
          echo "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" >> ./.env
          echo "AZURE_OPENAI_DEPLOYMENT_NAME=${{ vars.AZURE_OPENAI_DEPLOYMENT_NAME }}" >> ./.env
          echo "AZURE_OPENAI_API_VERSION=${{ vars.AZURE_OPENAI_API_VERSION }}" >> ./.env
          echo "AZURE_USERNAME=${{ secrets.AZURE_USERNAME }}" >> ./.env
          echo "AZURE_PASSWORD=${{ secrets.AZURE_PASSWORD }}" >> ./.env
          echo "LLAMA_CLOUD_API_KEY=${{ secrets.LLAMA_CLOUD_API_KEY }}" >> ./.env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ./.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ./.env
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> ./.env
          echo "FLASK_SESSION_KEY=${{ secrets.FLASK_SESSION_KEY }}" >> ./.env
          echo "COSMOS_ENDPOINT=${{ vars.COSMOS_ENDPOINT }}" >> ./.env

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Archive the application
      - name: Archive application
        run: |
          zip -r app.zip .

      # Deploy to Azure App Service
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rcaapi'
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C8146096A00E441D8F5B40D1B4D77EFD }}
          package: ./app.zip
